name: Task Template
description: Create a new task
title: 'Task'
labels: ['task']
projects: ['']
body:
  - type: textarea
    id: task-description
    attributes:
      label: Description of the Task
      description: Provide a brief Description what has to be done
    validations:
      required: true
